# Generated by Django 5.0.2 on 2024-02-07 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_update_at_alter_post_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
