# Generated by Django 5.0.1 on 2024-02-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_remove_eventmodel_ecolor_remove_eventmodel_eicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3)),
                ('value_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='edate',
            field=models.CharField(max_length=100),
        ),
    ]
