# Generated by Django 5.0.1 on 2024-02-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_weather_value_alter_eventmodel_edate'),
    ]

    operations = [
        migrations.CreateModel(
            name='today_weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=8)),
                ('information', models.CharField(max_length=10)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Weather_Value',
        ),
    ]
