# Generated by Django 5.0.1 on 2024-02-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rank',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
