# Generated by Django 5.0.1 on 2024-02-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_restaurant_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
