# Generated by Django 5.0.1 on 2024-02-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='edate',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='edate_e',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='edate_s',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='user_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
